configfile: "config/config.yml"



rule download_data:
  input:
    "resources/data/datasets.txt"
  output:
    directory("results/data/downloads/")
  shell:
    "wget -i {input} -P {output}"

rule unzip_structure_files:
  input:
    "results/data/downloads/ma-bak-cepc?type=materials_procedures__accompanying_data_file_name"
  output:
    directory("results/data/raw/structures")
  shell:
    "unzip {input} -d {output}"
    
rule annotate_proteins_kegg:
  conda:
    "envs/kegg.yaml"
  input:
    "resources/data/metadata.csv"
  output:
    "results/data/queries/kegg/pathways.csv"
  script:
    "scripts/queries/fetch-kegg-pathways.R"
    
rule run_explore:
  conda:
      "envs/kegg.yaml"
  input:
    "resources/data/metadata.csv",
    "results/data/queries/kegg/kegg-pathways.csv",
    "results/data/queries/uniprot/primary-go-annotation.csv"
  script:
    "scripts/analysis/exploration.R"

rule annotate_proteins:
  conda:
    "envs/bio.yaml"
  input:
    "resources/data/metadata.csv"
  output:
    "results/data/queries/uniprot/primary-go-annotation.csv"
  script:
    "scripts/construct/annotate_uniprot.py"
