[project]
name = "yeast-computational-pi-screen"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sibbe Bakker <sibbe.bakker@wur.nl>"]
channels = ["conda-forge", "bioconda", "Pypi", "PyPi", "pypi"]
platforms = ["linux-64"]

[tasks]

[dependencies]
conda = ">=24.3.0,<24.4"
snakemake = ">=8.10.7,<8.11"
tree = ">=2.1.1,<2.2"
oxigraph-server = ">=0.3.22,<0.4"
biopython = ">=1.83,<2"
rdflib = ">=7.0.0,<7.1"
polars = ">=0.20.21,<0.21"
mamba = ">=1.5.8,<1.6"
ipython = ">=8.22.2,<8.23"
[system-requirements]
linux="4.18"
